# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{deris}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Garry Shutler"]
  s.date = %q{2010-06-07}
  s.description = %q{Simple documentation creation engine based on HAML}
  s.email = %q{garry@robustsoftware.co.uk}
  s.files = [
    "lib/deris.rb",
     "lib/file.rb",
     "lib/project.rb"
  ]
  s.homepage = %q{http://github.com/gshutler/deris}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple documentation creation engine based on HAML}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 2.2.0"])
    else
      s.add_dependency(%q<haml>, [">= 2.2.0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 2.2.0"])
  end
end

